global using AI.Shared.Constants;
global using AI.Shared.Utilities;
global using Demo.AI_Agents;
global using Demo.AI_Agents.Clients;
global using Microsoft.Agents.AI;
global using Microsoft.Extensions.AI;
global using OpenAI;
global using OpenAI.Chat;
global using OpenAI.Responses;
global using System.ClientModel;
global using System.Text;
global using System.Text.Json;
global using MicrosoftAIMessage = Microsoft.Extensions.AI;
