global using AI.Chatbot.Telemetry.Constants;
global using AI.Shared.Constants;
global using AI.Shared.Utilities;
global using Microsoft.Agents.AI;
global using OpenAI.Chat;
global using OpenTelemetry;
global using OpenTelemetry.Resources;
global using OpenTelemetry.Trace;
global using System.Diagnostics;